version: '3.3'
services:
    valtimo_openzaak:    
        image: openzaak/open-zaak
        environment:
            - DB_HOST=valtimo_openzaak_postgis
            - SECRET_KEY=veryRestrictedSecretKey
            - DB_USER=openzaak
            - DB_PASSWORD=openzaak 
            - CACHE_DEFAULT=valtimo_openzaak_redis:6379/0
            - CACHE_AXES=valtimo_openzaak_redis:6379/0
            - DEBUG=true 
            - ALLOWED_HOSTS=localhost
        ports:
            - 8000:8000
    valtimo_openzaak_postgis:
        image: postgis/postgis
        environment:
            - POSTGRES_USER=openzaak 
            - POSTGRES_PASSWORD=openzaak 
            - POSTGRES_DB=openzaak
    valtimo_openzaak_redis:
        image: redis
    valtimo_keycloak:
        image: ritense/valtimo-keycloak:0.0.2
        ports:
            - 8081:8080
    valtimo_database:
        image: mysql:5.7
        command: --lower_case_table_names=1 --sql_mode=NO_ENGINE_SUBSTITUTION
        environment:
            - MYSQL_ROOT_PASSWORD=demo
            - MYSQL_DATABASE=valtimo
        ports: 
            - 3306:3306
    valtimo_server:
        image: ritense/valtimo-server:0.0.2
    valtimo_console:
        image: ritense/valtimo-console:0.0.1
    valtimo_nginx:
        image: ritense/valtimo-nginx:0.0.7
        ports:
            - 80:80
        depends_on:
            - valtimo_server
            - valtimo_keycloak
            - valtimo_console